### ISSUE TITLE
[YMDK Air40] For people who have problem loading the "CONFIGURE" tab, here is the solution.

### ISSUE THREAD

**Issue by nyngwang** [the-via/app#254]
Create a .json file (there is a Google Drive link but it will not be future-proof) with the content I provided below. Then, go to the VIA page "DESIGN" tab (the brushes) and check/toggle/enable the "Use V2 definitions (deprecated)". There might be some warnings/errors sometimes but let's just ignore them, lol.

Anyway, I opened this because I got an authoritative message from the VIA Discord server saying there is no existing working JSON file for this keyboard, thus the auto-detection failure.

## A picture for the second step.

<img src="https://github.com/the-via/app/assets/24765272/f629bab3-8e51-4166-a79e-d4f5fc2fee31" width="400">

## Air40.json

```json
{
    "name": "Air40",
    "vendorId": "0x45D4",
    "productId": "0x0911",
    "lighting": "qmk_backlight_rgblight",
    "matrix": {
      "rows": 4,
      "cols": 12
    },
    "layouts": { 
      "keymap":
[
  [
    "0,0\n\n\n\n\n\n\n\n\nTab",
    "0,1\n\n\n\n\n\n\n\n\nQ",
    "0,2\n\n\n\n\n\n\n\n\nW",
    "0,3\n\n\n\n\n\n\n\n\nE",
    "0,4\n\n\n\n\n\n\n\n\nR",
    "0,5\n\n\n\n\n\n\n\n\nT",
    "0,6\n\n\n\n\n\n\n\n\nY",
    "0,7\n\n\n\n\n\n\n\n\nU",
    "0,8\n\n\n\n\n\n\n\n\nI",
    "0,9\n\n\n\n\n\n\n\n\nO",
    "0,10\n\n\n\n\n\n\n\n\nP",
    "0,11\n\n\n\n\n\n\n\n\nBack Space"
  ],
  [
    "1,0\n\n\n\n\n\n\n\n\nEsc",
    "1,1\n\n\n\n\n\n\n\n\nA",
    "1,2\n\n\n\n\n\n\n\n\nS",
    "1,3\n\n\n\n\n\n\n\n\nD",
    "1,4\n\n\n\n\n\n\n\n\nF",
    "1,5\n\n\n\n\n\n\n\n\nG",
    "1,6\n\n\n\n\n\n\n\n\nH",
    "1,7\n\n\n\n\n\n\n\n\nJ",
    "1,8\n\n\n\n\n\n\n\n\nK",
    "1,9\n\n\n\n\n\n\n\n\nL",
    "1,10\n\n\n\n\n\n\n\n\n;",
    "1,11\n\n\n\n\n\n\n\n\n'"
  ],
  [
    "2,0\n\n\n\n\n\n\n\n\nShift",
    "2,1\n\n\n\n\n\n\n\n\nZ",
    "2,2\n\n\n\n\n\n\n\n\nX",
    "2,3\n\n\n\n\n\n\n\n\nC",
    "2,4\n\n\n\n\n\n\n\n\nV",
    "2,5\n\n\n\n\n\n\n\n\nB",
    "2,6\n\n\n\n\n\n\n\n\nN",
    "2,7\n\n\n\n\n\n\n\n\nM",
    "2,8\n\n\n\n\n\n\n\n\n,",
    "2,9\n\n\n\n\n\n\n\n\n.",
    "2,10\n\n\n\n\n\n\n\n\n/",
    "2,11\n\n\n\n\n\n\n\n\nReturn"
  ],
  [
    "3,0",
    "3,1\n\n\n\n\n\n\n\n\nCtrl",
    "3,2\n\n\n\n\n\n\n\n\nAlt",
    "3,3\n\n\n\n\n\n\n\n\nSuper",
    "3,4\n\n\n\n\n\n\n\n\n&dArr;",
    "3,5",
    "3,6",
    "3,7\n\n\n\n\n\n\n\n\n&uArr;",
    "3,8\n\n\n\n\n\n\n\n\n&larr;",
    "3,9\n\n\n\n\n\n\n\n\n&darr;",
    "3,10\n\n\n\n\n\n\n\n\n&uarr;",
    "3,11\n\n\n\n\n\n\n\n\n&rarr;"
  ]
]
}
  }
```

**Comment by Cipulot** [comment]
The issue, as mentioned in the VIA server by other people, was that the maintainer of the board, `YMDK`, only merged the `YMD40 v2` and seemingly not the `YMD40 v1`, or `Air40` if that is the name that they used.

The suggestion made was to update the firmware if the board was instead the `YMD40 v2` since that might solve the issue of outdated firmware with mismatching info with the ones in the VIA keyboards repository.

If this `is` indeed a different board from the `YMD40 v2` then that should be addressed by opening a PR over in the https://github.com/the-via/keyboards/ repository, checking that all the PR merging requirements are satisfied.

Cheers.
